### PR TITLE
Theme 2019 - stage 1

### PR DESCRIPTION
**Pull request by darek-grund**
First stage of theme 2019

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by WTobor** [comment]
What about this view (main page)?
image

**Comment by WTobor** [comment]
Prizes: why everything is on the left?
image

**Comment by WTobor** [comment]
Can we change colors in this footer (remove this blue one)?
image

**Comment by WTobor** [comment]
I cannot see _Register_ and _Login_ page
image
How you did that? I just just removed comment in
```
<div>
        @await Html.PartialAsync("_LoginPartial")
    </div>
```

**Comment by WTobor** [comment]
- Privacy: 👍 
- Contact: 👍 
- About: 👍 

- Prizes: 👎 (wrong layout?)
- Login 👎 (cannot see the view)
- Register 👎 (cannot see the view)

Did I miss something?

**Comment by darek-grund** [comment]
> Prizes: why everything is on the left?
> image

**It looks like old html markup but with updated styles. It should look like image below:**
image
I just doble check and it looks ok on my end - I wasn't able to replicate this problem. Could you please check if the problem still exists?

**Comment by darek-grund** [comment]
> Can we change colors in this footer (remove this blue one)?
> image

Fixed with https://github.com/DevAdventCalendar/DevAdventCalendar/pull/161/commits/546a9a44de8f7db7b0f01d9eacec83814c1a55df

**Comment by darek-grund** [comment]
> I cannot see _Register_ and _Login_ page
> image
> How you did that? I just enabled the code in __Layout.cshtml_
> 
> ```
> <div>
>    @await Html.PartialAsync("_LoginPartial")
> </div>
> ```
This is bug related to this issue: https://github.com/DevAdventCalendar/DevAdventCalendar/issues/163 - I've noticed it happens on develop branch but not on master branch.

**Comment by WTobor** [comment]
> > Prizes: why everything is on the left?
> I just doble check and it looks ok on my end - I wasn't able to replicate this problem. Could you please check if the problem still exists?

Ok, now it worked and looks great!

**Comment by WTobor** [comment]
> > Can we change colors in this footer (remove this blue one)?
> > image
> 
> Fixed with [546a9a4](https://github.com/DevAdventCalendar/DevAdventCalendar/commit/546a9a44de8f7db7b0f01d9eacec83814c1a55df)

Am I right, that this white one is 1px bigger? But it is not a big matter. Looks good :)

**Comment by WTobor** [comment]
> I've noticed this bug is already fixed on branch develop. I did merge with develop branch so it is also fixed on feature/theme-2019 branch
It works now!
Can you just align better external login providers' buttons? Maybe matrix 2x2 will be good? Could you make the button bigger and align the icon in the middle?

**Comment by WTobor** [comment]
image
Could you make sth with this in a small resolution? We can discuss which resolution can be minimal for us.

**Comment by WTobor** [comment]
image
The same here - problem with a small resolution on the main page

**Comment by WTobor** [comment]
And last question: why `register` is always white? Other menu items have different color

**Comment by darek-grund** [comment]
> > > Can we change colors in this footer (remove this blue one)?
> > > image
> > 
> > 
> > Fixed with [546a9a4](https://github.com/DevAdventCalendar/DevAdventCalendar/commit/546a9a44de8f7db7b0f01d9eacec83814c1a55df)
> 
> Am I right, that this white one is 1px bigger? But it is not a big matter. Looks good :)

Fixed with https://github.com/DevAdventCalendar/DevAdventCalendar/pull/161/commits/fe1b9ce89ed1a7f1bca2ba01aef0d6a3da15c0cb

**Comment by darek-grund** [comment]
> > I've noticed this bug is already fixed on branch develop. I did merge with develop branch so it is also fixed on feature/theme-2019 branch
> > It works now!
> > Could you just align better external login providers' buttons? Maybe matrix 2x2 will be good? Could you make the button bigger and align the icon in the middle?

What is "external login providers"? Also please add enhancements to separate list - I will do them in bulk when the new layout is ready

**Comment by darek-grund** [comment]
> And last question: why `register` is always white? Other menu items have different color

It is to separate it from other links and make it noticable

**Comment by darek-grund** [comment]
> image
> The same here - problem with a small resolution on the main page

Fixed with https://github.com/DevAdventCalendar/DevAdventCalendar/pull/161/commits/9a584319b5dfc2315fad634a3cc681f8b3f14905

**Pull request merged**
