### PR TITLE
Add 2020 awards

### PR DESCRIPTION
**Pull request by Mejtika**
## Screenshots (if appropriate)
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by WTobor** [comment]
@Mejtika please remove info about "Chcesz zostać partnerem...?" and remove images with last years' prizes

**Review by WTobor — APPROVED** [review]

**Comment by Quer1234** [comment]
Looking at the information at the screen, there is visible - 'Wypaśny tablet, słuchawki, głosniki'

Should be 'głośniki' instead of 'głosniki'

**Comment by Quer1234** [comment]
In section nagrody tygodni, image for price Helion is not visible
image

**Comment by WTobor** [comment]
@Mejtika could you please add a quick fix today?

**Pull request merged**
