### PR TITLE
Wrong answer to the question - showing our answer in the message

### PR DESCRIPTION
**Pull request by bananbe**
## Description
I have extended the dto passed to view, so from now on it contains a user's answer, thus in can be shown when needed (user provides wrong answer).

## Where should the reviewer start?
I would suggest to check [Index.cshtml](https://github.com/DevAdventCalendar/DevAdventCalendar/blob/develop/src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Test/Index.cshtml) and later corresponding controller.

## Motivation and context
There is a request from users to know if they did eg. a typo when providing the answer. Related issue #266

## How has this been tested?
I have added test case in unit tests and did a manual testing.

## Screenshots (if appropriate)
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by WTobor** [comment]
Hi :) Thank you for contribution ❤️ 
@szrtGreg will review PR tomorrow

**Comment by szrtGreg** [comment]
Good Morning,
Changes look good. I was able to get same results, Test are passing, All Resources are in place. Good job 👍  If I were you I would only slightly change UnitTest - However your test is 100% correct. 

1) move usersWrongAnswer to Arrange seciton
2) For me that way Assert is more readable

obraz


Have a lovely day :)

**Review by szrtGreg — COMMENTED** [review]
Please check my log comment

**Comment by bananbe** [comment]
I have changed the code as you suggested :)

**Comment by WTobor** [comment]
@bananbe please resolve conflicts and I will complete PR :)

**Comment by bananbe** [comment]
@WTobor I have rebased my branch on top of develop and resolved conflicts.

**Review by WTobor — APPROVED** [review]

**Pull request merged**
