### PR TITLE
GitHub actions redo

### PR DESCRIPTION
**Pull request by michalchecinski**
## Description
Added new checks for pr validation: build and test project before docker build.

## Motivation and context
Checking if docker image will be build is not so efficient. Author of PR should immidiately know if sth is not working outside of her/his local setup. For that I've added two steps to validate build and test solution.

## How has this been tested?
Was run on PRs in my fork.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by michalchecinski** [comment]
Could you tell me the reason why there was a docker build as check for PR? Maybe you have some issues that code was working, but the docker won't build the container? The docker build is time-consuming, and I think that dotnet build & test should be enough for PR validating. But I want to know the context why that check was present. That's also the reason why I left it the way it was :)

**Comment by WTobor** [comment]
@plotzwi could You add a comment? :)

**Comment by patrikulus** [comment]
We use build container pattern. Have you seen what's inside the Dockerfile? We build and test app during image build. Those steps you've added are redundant. This approach also assures us that PR won't break the docker image build.

**Comment by michalchecinski** [comment]
Yep, I've seen dockerfile. But I think that PR build should fail fast. Docker build is not so fast :) But it's only my point of view. If the way it is works great :)

**Comment by WTobor** [comment]
@patrikulus could you decide what to do and check or close PR?

**Comment by WTobor** [comment]
Closed due to inactivity

**Pull request closed without merging**
