### PR TITLE
Added codecov integration

### PR DESCRIPTION
**Pull request by patrikulus**
Added integration with codecov.io

## Description
Pipeline sends now code coverage report to codecov.io

## Where should the reviewer start?
Check dotnet test parameters, run the action

## Motivation and context
#285 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by patrikulus** [comment]
Not working yet, please do not merge

**Comment by WTobor** [comment]
@patrikulus - do you have an update?

**Comment by WTobor** [comment]
@lkurzyniec could you help with that?

**Comment by lkurzyniec** [comment]
@WTobor fix in #292

**Pull request merged**
